---
- name: Deploy loopback configuration
  hosts: R1
  gather_facts: false
  connection: local

  vars:
   cli:
    username: cisco
    password: cisco
    auth_pass: cisco

  tasks:
    - name: Deploy lo1 interface
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: interface lo1
        lines:
          - ip address 99.99.99.99 255.255.255.255

      register: print_output
    -  debug: var=print_output

   