---
- name: get ARP information
  hosts: all
  gather_facts: false

  tasks:
    - name: show ARP table
      raw: "show arp"

      register: print_output

    - debug: var=print_output.stdout_lines