---
- name: get CDP information
  hosts: all
  gather_facts: false

  tasks:
    - name: show CDP neighbors
      raw: "show cdp nei"

      register: print_output

    - debug: var=print_output.stdout_lines