---
- name: get device info
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Get interface info
      ios_command:
        commands:
          - show ip int br

      register: print_output
    - debug: var=print_output.stdout_lines

    - name: Get RIB BGP info
      ios_command:
        commands:
          - show ip route bgp

      register: print_output
    - debug: var=print_output.stdout_lines

    - name: save output to file
      copy: content="{{ print_output.stdout[0] }}" dest="/root/output/{{ inventory_hostname }}"